### ISSUE TITLE
Question:  Is SimpleCLI a blocking library?

### ISSUE THREAD

**Issue by intensite** [spacehuhn/SimpleCLI#7]
Very nice library!

My question is, can the controller do other things, while it processes the text as it is arriving?

**Comment by spacehuhn** [comment]
Thanks, good question.

This is like any other arduino library or code, so yes it's blocking.
To be more specific, calling `parse` is blocking (https://github.com/spacehuhn/SimpleCLI#parsing-input).
If you need to run things async then you'll need to put that call in a seperate thread or on another core, depending on your hardware and toolchain.
The other code is of course also blocking, but that's usually not a problem, since you only add your commands once in the `setup` function.

**Comment by intensite** [comment]
After I studied some of your examples, I recognize my question was not so good.

I should not be worried about your library but about the 
```String input = Serial.readString();```

**Comment by spacehuhn** [comment]
In that case, have a look at [`readStringUntil`](https://www.arduino.cc/reference/tr/language/functions/communication/serial/readstringuntil/) and ['setTimeout'](https://www.arduino.cc/reference/en/language/functions/communication/serial/settimeout/). 
I often use `readStringUntil('\n')`
